from config.load_config import ENV

DEV_MODE = ENV["DEV_MODE"]

OLLAMA_BASE_URL = ENV["OLLAMA_BASE_URL"]
POSTGIS_HOST = ENV["POSTGIS_HOST"]
POSTGIS_PORT = ENV["POSTGIS_PORT"]

if DEV_MODE == "true":
    # Local development
    OLLAMA_BASE_URL = ENV["DEV_OLLAMA_BASE_URL"]
    POSTGIS_HOST = ENV["DEV_POSTGIS_HOST"]
    POSTGIS_PORT = ENV["DEV_POSTGIS_PORT"]
